### ISSUE TITLE
Magento 1 module Fatal Error after Data Migration

### ISSUE THREAD

**Issue by beckindesigns** [magento/data-migration-tool#127]
This is probably not an issue with this tool at all but I figured this would be the best place to get an understanding of what is happening here. After doing the first initial data migration, I get the following fatal error / report after finishing. Note: I did not receive any errors in shell during the migration.

```
a:4:{i:0;s:127:"Warning: Illegal string offset '' in /home/myuser/public_html/vendor/magento/framework/App/Config/Scope/Converter.php on line 41";i:1;s:6480:"#0 /home/myuser/public_html/vendor/magento/framework/App/Config/Scope/Converter.php(41): Magento\Framework\App\ErrorHandler->handler(2, 'Illegal string ...', '/home/mage2/pub...', 41, Array)
#1 /home/mage2/public_html/vendor/magento/framework/App/Config/Scope/Converter.php(22): Magento\Framework\App\Config\Scope\Converter->_setArrayValue(Array, 'lookbookslider/...', 'default/hotspot...')
```

The lookbookslider is a module from the original v1 site. Where is it getting this data that is causing the issue on the Magento 2 side? How can it be ignored?

**Comment by beckindesigns** [comment]
NVM

I found it was pulling that info from the imported settings table.
