### ISSUE TITLE
Categories broken after migration 1.9.2.2 to 2.1.0

### ISSUE THREAD

**Issue by onepack** [magento/data-migration-tool#130]
On the frontend I have a 404 on every category and in the backend I get the error mentioned underneath when opening a category for editing

1 exception(s):
Exception #0 (Exception): Notice: Undefined offset: 230 in /apps/web/dev3.site.com/public_html/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166

Exception #0 (Exception): Notice: Undefined offset: 230 in /apps/web/dev3.site.com/public_html/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166
#0 /apps/web/dev3.site.com/public_html/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php(166): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined offse...', '/apps/web/dev3....', 166, Array)
#1 /apps/web/dev3.site.com/public_html/vendor/magento/framework/EntityManager/Operation/Read/ReadAttributes.php(59): Magento\Eav\Model\ResourceModel\ReadHandler->execute('Magento\\Catalog...', Array, Array)
#2 /apps/web/dev3.site.com/public_html/vendor/magento/framework/EntityManager/Operation/Read.php(116): Magento\Framework\EntityManager\Operation\Read\ReadAttributes->execute(Object(Magento\Catalog\Model\Category\Interceptor), Array)
#3 /apps/web/dev3.site.com/public_html/vendor/magento/framework/EntityManager/EntityManager.php(61): Magento\Framework\EntityManager\Operation\Read->execute(Object(Magento\Catalog\Model\Category\Interceptor), 3, Array)
#4 /apps/web/dev3.site.com/public_html/vendor/magento/module-catalog/Model/ResourceModel/Category.php(996): Magento\Framework\EntityManager\EntityManager->load(Object(Magento\Catalog\Model\Category\Interceptor), 3)
#5 /apps/web/dev3.site.com/public_html/vendor/magento/framework/Model/AbstractModel.php(531): Magento\Catalog\Model\ResourceModel\Category->load(Object(Magento\Catalog\Model\Category\Interceptor), 3, NULL)
#6 /apps/web/dev3.site.com/public_html/vendor/magento/module-catalog/Controller/Adminhtml/Category.php(40): Magento\Framework\Model\AbstractModel->load(3)
#7 /apps/web/dev3.site.com/public_html/vendor/magento/module-catalog/Controller/Adminhtml/Category/Edit.php(75): Magento\Catalog\Controller\Adminhtml\Category->_initCategory(true)
#8 /apps/web/dev3.site.com/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Category\Edit->execute()
#9 /apps/web/dev3.site.com/public_html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /apps/web/dev3.site.com/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /apps/web/dev3.site.com/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->___callParent('dispatch', Array)
#12 /apps/web/dev3.site.com/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Array, 'adminAuthentica...')
#13 /apps/web/dev3.site.com/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /apps/web/dev3.site.com/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /apps/web/dev3.site.com/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Array, 'adminMassaction...')
#16 /apps/web/dev3.site.com/public_html/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /apps/web/dev3.site.com/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /apps/web/dev3.site.com/public_html/var/generation/Magento/Catalog/Controller/Adminhtml/Category/Edit/Interceptor.php(26): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#19 /apps/web/dev3.site.com/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /apps/web/dev3.site.com/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /apps/web/dev3.site.com/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#22 /apps/web/dev3.site.com/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#23 /apps/web/dev3.site.com/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /apps/web/dev3.site.com/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /apps/web/dev3.site.com/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#26 /apps/web/dev3.site.com/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /apps/web/dev3.site.com/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#28 /apps/web/dev3.site.com/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#29 {main}

**Comment by onepack** [comment]
I found that there were more people with this issue and found a part of the solution in the underneath thread:
https://github.com/magento/magento2/issues/5236

Apparently "Undefined offset: 230" stands for the attribute ID that is referenced by magento but is not longer present but still referred by in the database.
Clearing that attribute_id in the database solves the issues I was having to access the category in the backend of magento. The frontend is still an issue giving me 404 pages on most of the category pages.
