### ISSUE TITLE
SSH Reindex seems broken after data migration

### ISSUE THREAD

**Issue by onepack** [magento/data-migration-tool#131]
Not longer able to reindex after successful data migration:

[user@server public_html]$ php bin/magento indexer:reindex

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Migration\Console\MigrateSettingsCommand::__construct() must be an instance of Migration\Config, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /apps/web/dev3.site.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /apps/web/dev3.site.com/public_html/vendor/magento/data-migration-tool/src/Migration/Console/MigrateSettingsCommand.php:24
Stack trace:
#0 /apps/web/dev3.site.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Migration\Console\MigrateSettingsCommand->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))
#1 /apps/web/dev3.site.com/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Migration\\Conso...', Array)
#2 /apps/web/dev3.site.com/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): M in /apps/web/dev3.site.com/public_html/vendor/magento/data-migration-tool/src/Migration/Console/MigrateSettingsCommand.php on line 24
[user@server public_html]$

**Comment by onepack** [comment]
The exact same error occurs when I flush the cache: php bin/magento cache:flush

**Comment by onepack** [comment]
I cleared:
var/cache
var/page_cache
var/di

It seems to work again now. Still not sure what caused the initial errors it but this seems to solve the cache and indexer issue.
