### ISSUE TITLE
Exception #0 (Exception): Notice: Undefined offset: 109 in vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool#165]
This is on viewing the home page.

According to my m1 database, eav_attribute 109 is:

msrp_enabled

This is missing from my m2 database. Their is no entry at 109, also their is no entry for group_price

This is my config.xml:

```
        <eav_attribute_groups_file>etc/ee-to-ee/eav-attribute-groups.xml.dist</eav_attribute_groups_file>
```

This is the error:

```
1 exception(s):
Exception #0 (Exception): Notice: Undefined offset: 109 in /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166

Exception #0 (Exception): Notice: Undefined offset: 109 in /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166
#0 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php(166): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined offse...', '/Users/ccarnell...', 166, Array)
#1 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/EntityManager/Operation/Read/ReadAttributes.php(59): Magento\Eav\Model\ResourceModel\ReadHandler->execute('Magento\\Catalog...', Array, Array)
#2 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/EntityManager/Operation/Read.php(116): Magento\Framework\EntityManager\Operation\Read\ReadAttributes->execute(Object(VaxLtd\Catalog\Model\Product\Interceptor), Array)
#3 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/EntityManager/EntityManager.php(61): Magento\Framework\EntityManager\Operation\Read->execute(Object(VaxLtd\Catalog\Model\Product\Interceptor), 3806, Array)
#4 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-catalog/Model/ResourceModel/Product.php(655): Magento\Framework\EntityManager\EntityManager->load(Object(VaxLtd\Catalog\Model\Product\Interceptor), 3806)
#5 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(258): Magento\Catalog\Model\ResourceModel\Product->load(Object(VaxLtd\Catalog\Model\Product\Interceptor), 3806, NULL)
#6 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Model/AbstractModel.php(531): Magento\Catalog\Model\ResourceModel\Product\Interceptor->load(Object(VaxLtd\Catalog\Model\Product\Interceptor), 3806, NULL)
#7 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\Model\AbstractModel->load(3806)
#8 /Users/ccarnell/Sites/vax-uk2/var/generation/VaxLtd/Catalog/Model/Product/Interceptor.php(2379): VaxLtd\Catalog\Model\Product\Interceptor->___callPlugins('load', Array, Array)
#9 /Users/ccarnell/Sites/vax-uk2/app/code/VaxLtd/CheckoutLimit/Model/Product/Limit/Validator/Type/ProductId.php(27): VaxLtd\Catalog\Model\Product\Interceptor->load(3806)
#10 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): VaxLtd\CheckoutLimit\Model\Product\Limit\Validator\Type\ProductId->__construct(Object(VaxLtd\CheckoutLimit\Helper\Config), Object(VaxLtd\Catalog\Model\Product\Interceptor))
#11 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('VaxLtd\\Checkout...', Array)
#12 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('VaxLtd\\Checkout...', Array)
#13 /Users/ccarnell/Sites/vax-uk2/var/generation/VaxLtd/CheckoutLimit/Model/Factory/Product/Limit/ValidatorTypeFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create('VaxLtd\\Checkout...', Array)
#14 /Users/ccarnell/Sites/vax-uk2/app/code/VaxLtd/CheckoutLimit/Model/Factory/Product/Limit/ValidatorType.php(64): VaxLtd\CheckoutLimit\Model\Factory\Product\Limit\ValidatorTypeFactory->create(Array)
#15 /Users/ccarnell/Sites/vax-uk2/app/code/VaxLtd/CheckoutLimit/Model/Factory/Product/Limit/ValidatorType.php(55): VaxLtd\CheckoutLimit\Model\Factory\Product\Limit\ValidatorType->create(Array)
#16 /Users/ccarnell/Sites/vax-uk2/app/code/VaxLtd/CheckoutLimit/Model/Product/Limit/Validator.php(26): VaxLtd\CheckoutLimit\Model\Factory\Product\Limit\ValidatorType->getInstance(Object(VaxLtd\CheckoutLimit\Helper\Config))
#17 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): VaxLtd\CheckoutLimit\Model\Product\Limit\Validator->__construct(Object(VaxLtd\CheckoutLimit\Model\Factory\Product\Limit\ValidatorType), Object(VaxLtd\CheckoutLimit\Helper\Config))
#18 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('VaxLtd\\Checkout...', Array)
#19 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('VaxLtd\\Checkout...')
#20 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('VaxLtd\\Checkout...')
#21 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'VaxLtd\\Checkout...', NULL, 'validator', 'VaxLtd\\Checkout...')
#22 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('VaxLtd\\Checkout...', Array, Array)
#23 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('VaxLtd\\Checkout...')
#24 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('VaxLtd\\Checkout...')
#25 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'VaxLtd\\Checkout...', NULL, 'checkoutHelper', 'VaxLtd\\Checkout...')
#26 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('VaxLtd\\Checkout...', Array, Array)
#27 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('VaxLtd\\Checkout...')
#28 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('VaxLtd\\Checkout...')
#29 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Checkou...', NULL, 'checkoutCart', 'Magento\\Checkou...')
#30 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Checkou...', Array, Array)
#31 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Checkou...')
#32 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Checkou...')
#33 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Checkou...', NULL, 'checkoutCart', 'Magento\\GoogleT...')
#34 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\GoogleT...', Array, Array)
#35 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\GoogleT...', Array)
#36 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Element/BlockFactory.php(45): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\GoogleT...', Array)
#37 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout/Generator/Block.php(257): Magento\Framework\View\Element\BlockFactory->createBlock('Magento\\GoogleT...', Array)
#38 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout/Generator/Block.php(237): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('Magento\\GoogleT...', Array)
#39 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout/Generator/Block.php(215): Magento\Framework\View\Layout\Generator\Block->createBlock('Magento\\GoogleT...', 'banner_impressi...', Array)
#40 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout/Generator/Block.php(124): Magento\Framework\View\Layout\Generator\Block->generateBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'banner_impressi...')
#41 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#42 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#43 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#44 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#45 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#46 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#47 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#48 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#49 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('page_content_he...')
#50 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-cms/Helper/Page.php(171): Magento\Framework\View\Layout\Interceptor->getBlock('page_content_he...')
#51 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-cms/Controller/Index/Index.php(43): Magento\Cms\Helper\Page->prepareResultPage(Object(Magento\Cms\Controller\Index\Index\Interceptor), 'home')
#52 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Cms/Controller/Index/Index/Interceptor.php(24): Magento\Cms\Controller\Index\Index->execute(NULL)
#53 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/Action/Action.php(102): Magento\Cms\Controller\Index\Index\Interceptor->execute()
#54 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#55 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Cms\Controller\Index\Index\Interceptor->___callParent('dispatch', Array)
#56 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'contextPlugin')
#57 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#58 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#59 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'customer-segmen...')
#60 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-customer-segment/Model/App/Action/ContextPlugin.php(81): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#61 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\CustomerSegment\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#62 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'customer-app-ac...')
#63 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#64 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#65 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'storeCheck')
#66 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#67 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#68 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'weee-app-action...')
#69 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#70 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#71 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'tax-app-action-...')
#72 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#73 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#74 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Cms/Controller/Index/Index/Interceptor.php(39): Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#75 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/FrontController.php(55): Magento\Cms\Controller\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#76 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#77 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#78 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#79 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#80 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#81 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#82 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#83 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#84 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#85 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#86 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#87 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#88 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#89 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#90 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#91 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#92 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#93 /Users/ccarnell/Sites/vax-uk2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#94 {main}

```

**Comment by craigcarnell** [comment]
```
INSERT INTO `eav_attribute` (`attribute_id`, `entity_type_id`, `attribute_code`, `attribute_model`, `backend_model`, `backend_type`, `backend_table`, `frontend_model`, `frontend_input`, `frontend_label`, `frontend_class`, `source_model`, `is_required`, `is_user_defined`, `default_value`, `is_unique`, `note`)
VALUES
	(109, 4, 'group_price', NULL, '', 'varchar', NULL, NULL, 'select', 'Apply MAP', NULL, '', 0, 0, '2', 0, NULL);
```

Fixes this, after conversion

**Comment by Somphpdeveloper** [comment]
Thanks @craigcarnell . This database query really help me and save my time as well.
