### ISSUE TITLE
Uncaught Error: Call to a member function getStructure() on boolean

### ISSUE THREAD

**Issue by twistedatrocity** [magento/data-migration-tool#251]
Magento CE 2.1.4  (migrating from Magento CE 1.8.1, database is remote)
Migration Tool 2.1.4
PHP 7.0.15
Mysql 5.7
Vanilla install via CLI.
The settings migrate works fine. Data migration fails. Have tried downgrading php to 5.6 and starting over with fresh install with exact same results. Have also tried removing var/cache var/generation and var/page-cache prior to running data migration command.

Below is output and stack trace:

```
php -f bin/magento migrate:settings -r /magento2/vendor/magento/data-migration-tool/etc/ce-to-ce/1.8.1.0/config.xml
Reset the current position of migration to start from the beginning

[2017-02-25 13:53:59][INFO][mode: settings][stage: integrity check][step: Settings Step]: started
100% [============================] Remaining Time: 1 sec
[2017-02-25 13:54:00][INFO][mode: settings][stage: integrity check][step: Stores Step]: started
100% [============================] Remaining Time: 1 sec
[2017-02-25 13:54:00][INFO][mode: settings][stage: data migration][step: Settings Step]: started
100% [============================] Remaining Time: 1 sec
[2017-02-25 13:54:01][INFO][mode: settings][stage: data migration][step: Stores Step]: started
100% [============================] Remaining Time: 1 sec
[2017-02-25 13:54:02][INFO][mode: settings][stage: volume check][step: Stores Step]: started
100% [============================] Remaining Time: 1 sec
[2017-02-25 13:54:02][INFO][mode: settings][stage: volume check][step: Stores Step]: Migration completed

php -f bin/magento migrate:data -r /magento2/vendor/magento/data-migration-tool/etc/ce-to-ce/1.8.1.0/config.xml    
Reset the current position of migration to start from the beginning

[2017-02-25 13:54:36][INFO][mode: data][stage: integrity check][step: Data Integrity Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:55:36][INFO][mode: data][stage: integrity check][step: EAV Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:55:38][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:55:40][INFO][mode: data][stage: integrity check][step: Map Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:56:08][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:56:08][INFO][mode: data][stage: integrity check][step: Log Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:56:09][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:56:09][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:56:09][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:56:09][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:56:09][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:56:09][INFO][mode: data][stage: setup triggers][step: Stage]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:56:24][INFO][mode: data][stage: data migration][step: EAV Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:56:28][INFO][mode: data][stage: volume check][step: EAV Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:56:38][INFO][mode: data][stage: data migration][step: Customer Attributes Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:56:46][INFO][mode: data][stage: volume check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-02-25 13:56:47][INFO][mode: data][stage: data migration][step: Map Step]: started
13% [===>------------------------] Remaining Time: 6 mins PHP Fatal error:  Uncaught Error: Call to a member function getStructure() on boolean in /magento2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/AbstractResource.php:200
Stack trace:
#0 /magento2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Destination.php(33): Migration\ResourceModel\AbstractResource->getPageSize('catalog_product...')
#1 /magento2/vendor/magento/data-migration-tool/src/Migration/Step/Map/Data.php(170): Migration\ResourceModel\Destination->saveRecords('catalog_product...', Object(Migration\ResourceModel\Record\Collection), false)
#2 /magento2/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php(73): Migration\Step\Map\Data->perform()
#3 /magento2/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php(116): Migration\Mode\AbstractMode->runStage(Object(Migration\Step\Map\Data), 'Map Step', 'data migration')
#4 /magento2/vendor/magento/data-migration-tool/src in /magento2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/AbstractResource.php on line 200
```

**Comment by twistedatrocity** [comment]
It's failing on the catalog_product_entity_media_gallery_value table.

The labels field in this table have a lot of NULL values if it matters at all.

```
[2017-02-25 20:04:06][DEBUG][mode: data][stage: data migration][step: Map Step][table: catalog_product_entity_media_gallery_value]: migrating
100% [============================] Remaining Time: 1 sec PHP Fatal error:  Uncaught Error: Call to a member function getStructure() on boolean
```

**Comment by twistedatrocity** [comment]
Apparently the data connection to remote mysql was the culprit. I dumped remote database and imported it to local mysql instance, adjusted migration config to point to local db for source, started over and it ran without issue.

/facepalm

**Comment by florincyberion** [comment]
The default pagesize in the tool is 50k. That can be quite much from some mysql servers. Setting bulk_size in config.xml to a more reasoable number seems to resolve the issue.(for me it worked with 1000)
