### ISSUE TITLE
After data migration we have issue with Base table or view not found: 1146 Table 'magento2.customer/entity' doesn't exist

### ISSUE THREAD

**Issue by robinmaster** [magento/data-migration-tool#313]
however customer_entity exists.

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.customer/entity' doesn't exist, query was: SELECT `customer/entity`.* FROM `customer/entity` WHERE (entity_id ='')
Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.customer/entity' doesn't exist

Can you help me.
Our magento are 2.1.7

**Comment by robinmaster** [comment]
complete path
2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.customer/entity' doesn't exist, query was: SELECT `customer/entity`.* FROM `customer/entity` WHERE (entity_id ='')
Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.customer/entity' doesn't exist

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.customer/entity' doesn't exist, query was: SELECT `customer/entity`.* FROM `customer/entity` WHERE (entity_id ='')
#0 /var/www/clients/client0/web5/web/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/clients/client0/web5/web/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /var/www/clients/client0/web5/web/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/clients/client0/web5/web/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `custome...', Array)
#4 /var/www/clients/client0/web5/web/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(465): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `custome...', Array)
#5 /var/www/clients/client0/web5/web/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(520): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `custome...', Array)
#6 /var/www/clients/client0/web5/web/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(756): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 /var/www/clients/client0/web5/web/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(954): Zend_Db_Adapter_Abstract->fetchRow(Object(Magento\Framework\DB\Select))
#8 /var/www/clients/client0/web5/web/vendor/magento/framework/Model/AbstractModel.php(531): Magento\Eav\Model\Entity\AbstractEntity->load(Object(Magento\Customer\Model\Customer\Interceptor), NULL, NULL)
#9 /var/www/clients/client0/web5/web/vendor/mirasvit/module-helpdesk/src/Helpdesk/Block/Contact/Form.php(155): Magento\Framework\Model\AbstractModel->load(NULL)
#10 /var/www/clients/client0/web5/web/vendor/mirasvit/module-helpdesk/src/Helpdesk/view/frontend/templates/contact/button.phtml(4): Mirasvit\Helpdesk\Block\Contact\Form->getCustomer()
#11 /var/www/clients/client0/web5/web/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/client...')
#12 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Mirasvit\Helpdesk\Block\Contact\Form), '/var/www/client...', Array)
#13 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/client...')
#14 /var/www/clients/client0/web5/web/vendor/mirasvit/module-helpdesk/src/Helpdesk/Block/Contact/Form.php(354): Magento\Framework\View\Element\Template->_toHtml()
#15 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Element/AbstractBlock.php(659): Mirasvit\Helpdesk\Block\Contact\Form->_toHtml()
#16 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#17 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('contact-button')
#18 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('contact-button')
#19 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('contact-button')
#20 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('before.body.end')
#21 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('before.body.end')
#22 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('before.body.end')
#23 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#24 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#25 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('page.wrapper')
#26 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#27 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('root')
#28 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout->renderElement('root')
#29 /var/www/clients/client0/web5/web/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
#30 /var/www/clients/client0/web5/web/var/generation/Magento/Framework/View/Layout/Interceptor.php(39): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#31 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#32 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#33 /var/www/clients/client0/web5/web/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#34 /var/www/clients/client0/web5/web/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#35 /var/www/clients/client0/web5/web/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#36 /var/www/clients/client0/web5/web/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#37 /var/www/clients/client0/web5/web/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#38 /var/www/clients/client0/web5/web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#39 /var/www/clients/client0/web5/web/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#40 /var/www/clients/client0/web5/web/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#41 /var/www/clients/client0/web5/web/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(26): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#42 /var/www/clients/client0/web5/web/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#43 /var/www/clients/client0/web5/web/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#44 /var/www/clients/client0/web5/web/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#45 {main}

Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.customer/entity' doesn't exist
#0 /var/www/clients/client0/web5/web/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/clients/client0/web5/web/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/clients/client0/web5/web/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#3 /var/www/clients/client0/web5/web/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /var/www/clients/client0/web5/web/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `custome...', Array)
#5 /var/www/clients/client0/web5/web/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(465): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `custome...', Array)
#6 /var/www/clients/client0/web5/web/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(520): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `custome...', Array)
#7 /var/www/clients/client0/web5/web/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(756): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#8 /var/www/clients/client0/web5/web/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(954): Zend_Db_Adapter_Abstract->fetchRow(Object(Magento\Framework\DB\Select))
#9 /var/www/clients/client0/web5/web/vendor/magento/framework/Model/AbstractModel.php(531): Magento\Eav\Model\Entity\AbstractEntity->load(Object(Magento\Customer\Model\Customer\Interceptor), NULL, NULL)
#10 /var/www/clients/client0/web5/web/vendor/mirasvit/module-helpdesk/src/Helpdesk/Block/Contact/Form.php(155): Magento\Framework\Model\AbstractModel->load(NULL)
#11 /var/www/clients/client0/web5/web/vendor/mirasvit/module-helpdesk/src/Helpdesk/view/frontend/templates/contact/button.phtml(4): Mirasvit\Helpdesk\Block\Contact\Form->getCustomer()
#12 /var/www/clients/client0/web5/web/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/client...')
#13 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Mirasvit\Helpdesk\Block\Contact\Form), '/var/www/client...', Array)
#14 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/client...')
#15 /var/www/clients/client0/web5/web/vendor/mirasvit/module-helpdesk/src/Helpdesk/Block/Contact/Form.php(354): Magento\Framework\View\Element\Template->_toHtml()
#16 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Element/AbstractBlock.php(659): Mirasvit\Helpdesk\Block\Contact\Form->_toHtml()
#17 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#18 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('contact-button')
#19 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('contact-button')
#20 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('contact-button')
#21 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('before.body.end')
#22 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('before.body.end')
#23 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('before.body.end')
#24 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#25 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#26 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('page.wrapper')
#27 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#28 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('root')
#29 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout->renderElement('root')
#30 /var/www/clients/client0/web5/web/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
#31 /var/www/clients/client0/web5/web/var/generation/Magento/Framework/View/Layout/Interceptor.php(39): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#32 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#33 /var/www/clients/client0/web5/web/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#34 /var/www/clients/client0/web5/web/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#35 /var/www/clients/client0/web5/web/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#36 /var/www/clients/client0/web5/web/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#37 /var/www/clients/client0/web5/web/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#38 /var/www/clients/client0/web5/web/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#39 /var/www/clients/client0/web5/web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#40 /var/www/clients/client0/web5/web/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#41 /var/www/clients/client0/web5/web/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#42 /var/www/clients/client0/web5/web/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(26): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#43 /var/www/clients/client0/web5/web/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#44 /var/www/clients/client0/web5/web/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#45 /var/www/clients/client0/web5/web/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#46 {main}
