### ISSUE TITLE
Source documents are not mapped

### ISSUE THREAD

**Issue by furqanabid** [magento/data-migration-tool#314]
I've started the data migration from Magento 1.9.3.0 to Magento 2.1.3 and it delivers the following error:

`[2017-06-05 08:49:43][ERROR]: Source documents are not mapped: imageoption,paybox_question_number,strikeiron_tax_rate`

----------------------------------------------

Here  is the command that i've run
`php bin/magento migrate:data -r vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.3.0/config.xml`

and the output is

```
Reset the current position of migration to start from the beginning

[2017-06-05 08:49:29][INFO][mode: data][stage: integrity check][step: Data Integrity Step]: started
100% [============================] Remaining Time: 1 sec
[2017-06-05 08:49:40][INFO][mode: data][stage: integrity check][step: EAV Step]: started
100% [============================] Remaining Time: 1 sec
[2017-06-05 08:49:41][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: 1 sec
[2017-06-05 08:49:41][INFO][mode: data][stage: integrity check][step: Map Step]: started
0% [>---------------------------] Remaining Time: 1 sec
100% [============================] Remaining Time: 1 sec
[2017-06-05 08:49:43][ERROR]: Source documents are not mapped: imageoption,paybox_question_number,strikeiron_tax_rate
[2017-06-05 08:49:43][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
100% [============================] Remaining Time: 1 sec
[2017-06-05 08:49:43][INFO][mode: data][stage: integrity check][step: Log Step]: started
100% [============================] Remaining Time: 1 sec
[2017-06-05 08:49:43][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
100% [============================] Remaining Time: 1 sec
[2017-06-05 08:49:43][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
100% [============================] Remaining Time: 1 sec
[2017-06-05 08:49:43][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
100% [============================] Remaining Time: 1 sec
[2017-06-05 08:49:43][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
100% [============================] Remaining Time: 1 sec
[2017-06-05 08:49:43][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
100% [============================] Remaining Time: 1 sec


  [Migration\Exception]
  Integrity Check failed

```

Can you please help me out to fix this issue?

**Comment by victor-v-rad** [comment]
Hi @furqanabid 

[There](http://devdocs.magento.com/guides/v2.1/migration/migration-troubleshooting.html) you can find your answer and probably to many other questions too if you read the entire guide ;)

**Comment by furqanabid** [comment]
Hi @victor-v-rad 

Thanks for letting me know about the solution. The Migration process has been complete successfully with no error in the terminal.

But, when i try to access the `Product->Catalog` or `Product->Categories`, it shows

```
There has been an error processing your request
Exception printing is disabled by default for security reasons.
```

Here is the log for `Product->Catalog` when i try to edit any product

```
a:4:{i:0;s:59:"Attribute with attributeCode "users_manual" does not exist.";i:1;s:10604:"#0 /vendor/magento/module-eav/Model/AttributeRepository.php(143): Magento\Eav\Model\AttributeRepository->get('catalog_product', 'users_manual')
#1 /vendor/magento/module-catalog/Model/Product/Attribute/Repository.php(103): Magento\Eav\Model\AttributeRepository->getList('catalog_product', Object(Magento\Framework\Api\SearchCriteria))
#2 /var/generation/Magento/Catalog/Model/Product/Attribute/Repository/Interceptor.php(37): Magento\Catalog\Model\Product\Attribute\Repository->getList(Object(Magento\Framework\Api\SearchCriteria))
#3 /vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php(492): Magento\Catalog\Model\Product\Attribute\Repository\Interceptor->getList(Object(Magento\Framework\Api\SearchCriteria))
#4 /vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php(467): Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\Eav->loadAttributes(Object(Magento\Eav\Model\Entity\Attribute\Group))
#5 /vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php(242): Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\Eav->getAttributes()
#6 /vendor/magento/module-catalog/Ui/DataProvider/Product/Form/ProductDataProvider.php(68): Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\Eav->modifyMeta(Array)
#7 /vendor/magento/framework/View/Element/UiComponentFactory.php(269): Magento\Catalog\Ui\DataProvider\Product\Form\ProductDataProvider->getMeta()
#8 /vendor/magento/framework/View/Element/UiComponentFactory.php(164): Magento\Framework\View\Element\UiComponentFactory->mergeMetadata('product_form', Array, false)
#9 /vendor/magento/framework/View/Layout/Generator/UiComponent.php(125): Magento\Framework\View\Element\UiComponentFactory->create('product_form', NULL, Array)
#10 /vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'product_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#11 /vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#12 /vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#13 /var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#14 /vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#15 /vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#16 /vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#17 /vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#18 /vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#19 /var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#20 /vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#21 /var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Catalog...')
#22 /vendor/magento/module-catalog/Controller/Adminhtml/Product/Edit.php(69): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Catalog...')
#23 /var/generation/Magento/Catalog/Controller/Adminhtml/Product/Edit/Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Product\Edit->execute()
#24 /vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->execute()
#25 /vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->___callParent('dispatch', Array)
#28 /vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Array, 'adminAuthentica...')
#29 /vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Array, 'adminMassaction...')
#32 /vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#33 /vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 /var/generation/Magento/Catalog/Controller/Adminhtml/Product/Edit/Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#35 /vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#36 /vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#38 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#39 /vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#40 /vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#41 /var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#42 /vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#43 /vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#44 /index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#45 {main}";s:3:"url";s:104:"/admin/catalog/product/edit/id/173/key/334b1386371b9089e8d43c1181d3e3bdd17eb734e265d54fabc71f7de403c5d6/";s:11:"script_name";s:10:"/index.php";}
![product-not-displaying](https://user-images.githubusercontent.com/8986699/26913372-db3cb1fa-4c33-11e7-8c8e-5d2d94675bf5.JPG)


```



Here is the log for `Product->Categories`

```
a:4:{i:0;s:169:"Notice: Undefined offset: 111 in /vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166";i:1;s:7782:"#0 /vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php(166): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined offse...', '/home/nineninen...', 166, Array)
#1 /vendor/magento/framework/EntityManager/Operation/Read/ReadAttributes.php(59): Magento\Eav\Model\ResourceModel\ReadHandler->execute('Magento\\Catalog...', Array, Array)
#2 /vendor/magento/framework/EntityManager/Operation/Read.php(116): Magento\Framework\EntityManager\Operation\Read\ReadAttributes->execute(Object(Magento\Catalog\Model\Category\Interceptor), Array)
#3 /vendor/magento/framework/EntityManager/EntityManager.php(61): Magento\Framework\EntityManager\Operation\Read->execute(Object(Magento\Catalog\Model\Category\Interceptor), 3, Array)
#4 /vendor/magento/module-catalog/Model/ResourceModel/Category.php(996): Magento\Framework\EntityManager\EntityManager->load(Object(Magento\Catalog\Model\Category\Interceptor), 3)
#5 /var/generation/Magento/Catalog/Model/ResourceModel/Category/Interceptor.php(336): Magento\Catalog\Model\ResourceModel\Category->load(Object(Magento\Catalog\Model\Category\Interceptor), 3, NULL)
#6 /vendor/magento/framework/Model/AbstractModel.php(531): Magento\Catalog\Model\ResourceModel\Category\Interceptor->load(Object(Magento\Catalog\Model\Category\Interceptor), 3, NULL)
#7 /var/generation/Magento/Catalog/Model/Category/Interceptor.php(1480): Magento\Framework\Model\AbstractModel->load(3, NULL)
#8 /vendor/magento/module-catalog/Controller/Adminhtml/Category.php(40): Magento\Catalog\Model\Category\Interceptor->load(3)
#9 /vendor/magento/module-catalog/Controller/Adminhtml/Category/Edit.php(75): Magento\Catalog\Controller\Adminhtml\Category->_initCategory(true)
#10 /var/generation/Magento/Catalog/Controller/Adminhtml/Category/Edit/Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Category\Edit->execute()
#11 /vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->execute()
#12 /vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->___callParent('dispatch', Array)
#15 /vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Array, 'adminAuthentica...')
#16 /vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Array, 'adminMassaction...')
#19 /vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /var/generation/Magento/Catalog/Controller/Adminhtml/Category/Edit/Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#22 /vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#25 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#26 /vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#29 /vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#31 /index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#32 {main}";s:3:"url";s:99:"/admin/catalog/category/index/key/2391ec71000e494102bf4531e67b6b2e3ff0eda945bc0f8f11643a7a0a921a47/";s:11:"script_name";s:10:"/index.php";}
```

Also i noticed that the product name and other data is not displaying on the main page (screenshot attached).

![product-not-displaying](https://user-images.githubusercontent.com/8986699/26913387-f510376e-4c33-11e7-855f-20e6213f2edd.JPG)

**Can you please explain how to fix it?**

**Comment by victor-v-rad** [comment]
Strange enough. I do not find the attribute "users_manual" in Magento1 or 2. Seems it was created either manually or by some extension. Even so, in average circumstances, it should not have been a cause of the error you mentioned.
