### ISSUE TITLE
How to import products without categories and stores??

### ISSUE THREAD

**Issue by OZZlE** [magento/data-migration-tool#326]
My config.xml:
vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.1.1/config.xml
```
    <options>
        <map_file>etc/ce-to-ce/1.9.1.1/map.xml.dist</map_file>
```

In my map.xml.dist:
vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.1.1/map.xml.dist
```
<map xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../map.xsd">
    <source>
        <document_rules>
            <!-- ... -->
            <ignore>
                <document>eav_entity_store</document>
            </ignore>
            <ignore>
                <document>catalog_category_product*</document>
            </ignore>
            <ignore>
                <document>catalog_product_index_website</document>
            </ignore>
            <ignore>
                <document>catalog_product_website</document>
            </ignore>
            <ignore>
                <document>core_store</document>
            </ignore>
            <ignore>
                <document>core_store_group</document>
            </ignore>
            <ignore>
                <document>core_website</document>
            </ignore>
            <ignore>
                <document>core_config_data</document>
            </ignore>
            <ignore>
                <document>catalog_category_*</document>
            </ignore>
       </document_rules>
    <destination>
        <document_rules>
            <ignore>
                <document>store</document>
            </ignore>
            <ignore>
                <document>store_group</document>
            </ignore>
            <ignore>
                <document>store_website</document>
            </ignore>
<!-- ... -->
```
also have in eav-map.xml:
```
<map xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../map.xsd">
    <source>
        <document_rules>
            <ignore>
                <document>eav_entity_store</document>
            </ignore>
            <ignore>
                <document>catalog_product_index_eav*</document>
            </ignore>
            <ignore>
                <document>catalog_product_index_website</document>
            </ignore>
            <ignore>
                <document>catalog_category_*</document>
            </ignore>
```
But still when I run the command: `sudo -H -u www-data php bin/magento migrate:data --reset vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.1.1/config.xml`

It seems to still import categories attached to old stores, when visiting categories in admin:
```
1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Requested store is not found

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Requested store is not found
#0 vendor/magento/module-store/Model/StoreManager.php(164): Magento\Store\Model\StoreRepository->getById('8')
#1 vendor/magento/module-cms/Model/ResourceModel/AbstractCollection.php(85): Magento\Store\Model\StoreManager->getStore('8')
#2 vendor/magento/module-cms/Model/ResourceModel/Block/Collection.php(30): Magento\Cms\Model\ResourceModel\AbstractCollection->performAfterLoad('cms_block_store', 'block_id')
#3 vendor/magento/framework/Data/Collection/AbstractDb.php(586): Magento\Cms\Model\ResourceModel\Block\Collection->_afterLoad()
#4 vendor/magento/framework/Data/Collection/AbstractDb.php(557): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#5 vendor/magento/module-catalog/Model/Category/Attribute/Source/Page.php(40): Magento\Framework\Data\Collection\AbstractDb->load()
#6 vendor/magento/module-catalog/Model/Category/DataProvider.php(271): Magento\Catalog\Model\Category\Attribute\Source\Page->getAllOptions()
#7 vendor/magento/framework/Interception/Interceptor.php(146): Magento\Catalog\Model\Category\DataProvider->getAttributesMeta(Object(Magento\Eav\Model\Entity\Type))
#8 var/generation/Magento/Catalog/Model/Category/DataProvider/Interceptor.php(52): Magento\Catalog\Model\Category\DataProvider\Interceptor->___callPlugins('getAttributesMe...', Array, Array)
#9 vendor/magento/module-catalog/Model/Category/DataProvider.php(174): Magento\Catalog\Model\Category\DataProvider\Interceptor->getAttributesMeta(Object(Magento\Eav\Model\Entity\Type))
#10 vendor/magento/framework/Interception/Interceptor.php(146): Magento\Catalog\Model\Category\DataProvider->prepareMeta(Array)
#11 var/generation/Magento/Catalog/Model/Category/DataProvider/Interceptor.php(26): Magento\Catalog\Model\Category\DataProvider\Interceptor->___callPlugins('prepareMeta', Array, Array)
#12 vendor/magento/module-catalog/Model/Category/DataProvider.php(161): Magento\Catalog\Model\Category\DataProvider\Interceptor->prepareMeta(Array)
#13 var/generation/Magento/Catalog/Model/Category/DataProvider/Interceptor.php(14): Magento\Catalog\Model\Category\DataProvider->__construct('category_form_d...', 'entity_id', 'id', Object(Magento\Ui\DataProvider\EavValidationRules), Object(Magento\Catalog\Model\ResourceModel\Category\CollectionFactory), Object(Magento\Store\Model\StoreManager), Object(Magento\Framework\Registry), Object(Magento\Eav\Model\Config), Object(Magento\Framework\App\Request\Http), Object(Magento\Catalog\Model\CategoryFactory), Object(Magento\Framework\Filesystem), Array, Array)
#14 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Magento\Catalog\Model\Category\DataProvider\Interceptor->__construct('category_form_d...', 'entity_id', 'id', Object(Magento\Ui\DataProvider\EavValidationRules), Object(Magento\Catalog\Model\ResourceModel\Category\CollectionFactory), Object(Magento\Store\Model\StoreManager), Object(Magento\Framework\Registry), Object(Magento\Eav\Model\Config), Object(Magento\Framework\App\Request\Http), Object(Magento\Catalog\Model\CategoryFactory), Object(Magento\Framework\Filesystem), Array, Array)
#15 vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Catalog...', Array)
#16 vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...', Array)
#17 vendor/magento/framework/View/Element/UiComponent/Argument/Interpreter/ConfigurableObject.php(60): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Catalog...', Array)
#18 var/generation/Magento/Framework/Data/Argument/InterpreterInterface/Proxy.php(95): Magento\Framework\View\Element\UiComponent\Argument\Interpreter\ConfigurableObject->evaluate(Array)
#19 vendor/magento/framework/Data/Argument/Interpreter/Composite.php(61): Magento\Framework\Data\Argument\InterpreterInterface\Proxy->evaluate(Array)
#20 vendor/magento/module-ui/Model/Manager.php(188): Magento\Framework\Data\Argument\Interpreter\Composite->evaluate(Array)
#21 vendor/magento/module-ui/Model/Manager.php(191): Magento\Ui\Model\Manager->evaluateComponentArguments(Array)
#22 vendor/magento/module-ui/Model/Manager.php(172): Magento\Ui\Model\Manager->evaluateComponentArguments(Array)
#23 vendor/magento/framework/View/Element/UiComponentFactory.php(144): Magento\Ui\Model\Manager->prepareData('category_form')
#24 vendor/magento/framework/View/Layout/Generator/UiComponent.php(124): Magento\Framework\View\Element\UiComponentFactory->create('category_form', NULL, Array)
#25 vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'category_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#26 vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#27 vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#28 var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#29 vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#30 vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#31 vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#32 vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#33 vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#34 var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#35 vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#36 var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Catalog...')
#37 vendor/magento/module-catalog/Controller/Adminhtml/Category/Edit.php(102): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Catalog...')
#38 var/generation/Magento/Catalog/Controller/Adminhtml/Category/Edit/Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Category\Edit->execute()
#39 vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->execute()
#40 vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#41 vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#42 vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->___callParent('dispatch', Array)
#43 vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Array, 'adminAuthentica...')
#44 vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#45 vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#46 vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Array, 'adminMassaction...')
#47 vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#48 vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#49 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Array, 'adminAutoLogin')
#50 vendor/vaimo/module-admin-auto-login/App/Action/Plugin/Authentication.php(109): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#51 vendor/magento/framework/Interception/Interceptor.php(142): Vaimo\AdminAutoLogin\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#52 var/generation/Magento/Catalog/Controller/Adminhtml/Category/Edit/Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#53 vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#54 vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#55 vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#56 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#57 vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#58 vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#59 var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#60 vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#61 vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\App\Http->launch()
#62 var/generation/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#63 vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#64 index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#65 {main}
```
I used the default map.xml.dist and modified it..

**Comment by victor-v-rad** [comment]
Hi @OZZlE 

Stores are migrated when you migrate 'settings'.

**Comment by OZZlE** [comment]
@victor-v-rad I don't want to migrate 'settings', I want to migrate only products, attributes and attribute sets, that's it..

we have a different structure on our new site for stores and categories..

**Comment by OZZlE** [comment]
Not really the best solution but it seems like you can only migrate everything except core_config_data and then modify stores and categories to the new structure and then run a delta migration and it won't destroy the new structure.

**Comment by victor-v-rad** [comment]
Yes. Right now the tool can migrate all or nothing. That said, you can ignore some attributes or tables in map files.  Also removing some of the steps from your config.xml also possible
