### ISSUE TITLE
After Migrating Magento 1.7 to 2.1.6 Customers tab getting error both front and back end

### ISSUE THREAD

**Issue by prestashoppay** [magento/data-migration-tool#359]
@victor-v-rad ,
We are facing the same issues after we migrated the data's from M1.7 to M2.1.6.
and also unable to view the customers in back office and unable to register the new users in front end.
We are getting the below error and we got the message successfully migrated.

`Fatal error: Uncaught Error: Call to undefined method Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend\Interceptor::getAllOptions() in D:\xampp\htdocs\magento21\vendor\magento\module-customer\Model\AttributeMetadataConverter.php:66 Stack trace: #0 D:\xampp\htdocs\magento21\vendor\magento\module-customer\Model\Metadata\CustomerMetadata.php(77): Magento\Customer\Model\AttributeMetadataConverter->createMetadataAttribute(Object(Magento\Customer\Model\Attribute)) #1 D:\xampp\htdocs\magento21\vendor\magento\module-customer\Model\Metadata\CustomerMetadata.php(109): Magento\Customer\Model\Metadata\CustomerMetadata->getAttributeMetadata('default_blog_ca...') #2 D:\xampp\htdocs\magento21\vendor\magento\module-customer\Model\Metadata\CachedMetadata.php(82): Magento\Customer\Model\Metadata\CustomerMetadata->getAllAttributesMetadata() #3 D:\xampp\htdocs\magento21\vendor\magento\module-customer\Ui\Component\Listing\AttributeRepository.php(66): Magento\Customer\Model\Metadata\CachedMetadata->getAllAttributesMetadata() #4 D:\xampp in D:\xampp\htdocs\magento21\vendor\magento\module-customer\Model\AttributeMetadataConverter.php on line 66`

Let me know your suggestions to find the issues.
Thanks

**Comment by prestashoppay** [comment]
@victor-v-rad ,

Is there any updates ..

**Comment by prestashoppay** [comment]
@FutureDragon ,

After migration m1.7 to m2.1, m2.1 Admin area click sales > order view getting below error,

Issues Lilsted ,

When I open the orders they show up but when I want to view an order I see this on a blank page:
Order View Information Changes have been made to this section that have not been saved. This tab contains inval...

Please check and let me any solutions.

**Comment by prestashoppay** [comment]
@FutureDragon ,

After migration m1.7 to m2.1 , m2.1 Admin area click Customers > All Customers view getting below error,

In frontend and backend when trying to create a new account I get a below error:

Fatal error: Uncaught Error: Call to undefined method Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend\Interceptor::getAllOptions() in D:\xampp\htdocs\magento21\vendor\magento\module-customer\Model\AttributeMetadataConverter.php:66 Stack trace: #0 D:\xampp\htdocs\magento21\vendor\magento\module-customer\Model\Metadata\CustomerMetadata.php(77): Magento\Customer\Model\AttributeMetadataConverter->createMetadataAttribute(Object(Magento\Customer\Model\Attribute)) #1 D:\xampp\htdocs\magento21\vendor\magento\module-customer\Model\Metadata\CustomerMetadata.php(109): Magento\Customer\Model\Metadata\CustomerMetadata->getAttributeMetadata('default_blog_ca...') #2 D:\xampp\htdocs\magento21\vendor\magento\module-customer\Model\Metadata\CachedMetadata.php(82): Magento\Customer\Model\Metadata\CustomerMetadata->getAllAttributesMetadata() #3 D:\xampp\htdocs\magento21\vendor\magento\module-customer\Ui\Component\Listing\AttributeRepository.php(66): Magento\Customer\Model\Metadata\CachedMetadata->getAllAttributesMetadata() #4 D:\xampp in D:\xampp\htdocs\magento21\vendor\magento\module-customer\Model\AttributeMetadataConverter.php on line 66

Please check and let me any solutions.
