### ISSUE TITLE
 Invalid parameter configuration provided for $sourceDocument argument of Migration\RecordTransformer 

### ISSUE THREAD

**Issue by CharanjeetE** [magento/data-migration-tool#651]
I am trying to migrate data from m1 to m2.3  and getting the following error.
### Preconditions

1. Running this command
  sudo php /var/www/m2.gocleaning.nl/bin/magento migrate:settings -r -a  /var/www/m2.gocleaning.nl/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.7/config.xml

2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

[2019-02-08 08:05:59][INFO][mode: settings][stage: integrity check][step: Settings Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-02-08 08:05:59][INFO][mode: settings][stage: integrity check][step: Stores Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-02-08 08:05:59][WARNING]: Source documents are not mapped: core_store,core_store_group,core_website
[2019-02-08 08:05:59][WARNING]: Destination documents are not mapped: store,store_group,store_website
[2019-02-08 08:05:59][INFO][mode: settings][stage: data migration][step: Settings Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-02-08 08:05:59][INFO][mode: settings][stage: data migration][step: Stores Step]: started
33% [=========>------------------] Remaining Time: < 1 sec
In AbstractFactory.php line 147:
                                                                                                        
  Invalid parameter configuration provided for $sourceDocument argument of Migration\RecordTransformer  
                                                                                                        

migrate:settings [-r|--reset] [-a|--auto] [--] <config>

[root@Gocleaning-m2 opensource-to-opensource]# sudo php /var/www/m2.gocleaning.nl/bin/magento migrate:settings -r -a -vvv  /var/www/m2.gocleaning.nl/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.7/config.xml
Reset the current position of migration to start from the beginning

[2019-02-08 08:11:13][INFO][mode: settings][stage: integrity check][step: Settings Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-02-08 08:11:13][INFO][mode: settings][stage: integrity check][step: Stores Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-02-08 08:11:13][WARNING]: Source documents are not mapped: core_store,core_store_group,core_website
[2019-02-08 08:11:13][WARNING]: Destination documents are not mapped: store,store_group,store_website
[2019-02-08 08:11:13][INFO][mode: settings][stage: data migration][step: Settings Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-02-08 08:11:13][INFO][mode: settings][stage: data migration][step: Stores Step]: started
33% [=========>------------------] Remaining Time: < 1 sec
In AbstractFactory.php line 147:
                                                                                                        
  [UnexpectedValueException]                                                                            
  Invalid parameter configuration provided for $sourceDocument argument of Migration\RecordTransformer  
                                                                                                        

Exception trace:
 () at /var/www/m2.gocleaning.nl/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:147
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/m2.gocleaning.nl/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:246
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /var/www/m2.gocleaning.nl/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/m2.gocleaning.nl/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/m2.gocleaning.nl/vendor/magento/framework/ObjectManager/ObjectManager.php:56
 Magento\Framework\ObjectManager\ObjectManager->create() at /var/www/m2.gocleaning.nl/generated/code/Migration/RecordTransformerFactory.php:43
 Migration\RecordTransformerFactory->create() at /var/www/m2.gocleaning.nl/vendor/magento/data-migration-tool/src/Migration/Step/Stores/Data.php:100
 Migration\Step\Stores\Data->perform() at /var/www/m2.gocleaning.nl/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php:81
 Migration\Mode\AbstractMode->runStage() at /var/www/m2.gocleaning.nl/vendor/magento/data-migration-tool/src/Migration/Mode/Settings.php:100
 Migration\Mode\Settings->runData() at /var/www/m2.gocleaning.nl/vendor/magento/data-migration-tool/src/Migration/Mode/Settings.php:58
 Migration\Mode\Settings->run() at /var/www/m2.gocleaning.nl/vendor/magento/data-migration-tool/src/Migration/Console/MigrateSettingsCommand.php:54
 Migration\Console\MigrateSettingsCommand->execute() at /var/www/m2.gocleaning.nl/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/m2.gocleaning.nl/vendor/symfony/console/Application.php:893
 Symfony\Component\Console\Application->doRunCommand() at /var/www/m2.gocleaning.nl/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /var/www/m2.gocleaning.nl/vendor/magento/framework/Console/Cli.php:102
 Magento\Framework\Console\Cli->doRun() at /var/www/m2.gocleaning.nl/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /var/www/m2.gocleaning.nl/bin/magento:23

migrate:settings [-r|--reset] [-a|--auto] [--] <config>

### Additional notes
I have exported the data from m1 server and imported in m2 server than trying to migrate from this data but getting errors.

**Comment by CharanjeetE** [comment]
Can I skip settings migration. What things will be migrated in settings? Can I continue with this.

**Comment by victor-v-rad** [comment]
Hi @CharanjeetE 

what is exact version of Magento 1 you are migrating?

**Comment by victor-v-rad** [comment]
settings migrates stores/websites and system configuration (core_config_data table)

**Comment by CharanjeetE** [comment]
1.9.3.7

**Comment by CharanjeetE** [comment]
I have checked that if I will skip settings migrate:data also giving errors
[2
019-02-08 12:30:39][INFO][mode: data][stage: integrity check][step: Data Integrity Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-02-08 12:30:40][INFO][mode: data][stage: integrity check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-02-08 12:30:40][WARNING]: Incompatibility in data. Source document: eav_attribute_group. Field: attribute_group_name. Error: The product attribute set "Default" does not contain all required attribute group names "General, Prices, Design, Images"
[2019-02-08 12:30:40][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-02-08 12:30:40][INFO][mode: data][stage: integrity check][step: Map Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-02-08 12:30:41][WARNING]: Source documents are not mapped: email_template,paypal_billing_agreement,paypal_billing_agreement_order,quote,quote_address,quote_address_item,quote_item,quote_item_option,quote_payment,quote_shipping_rate,sales_creditmemo,sales_creditmemo_comment,sales_creditmemo_item,sales_invoice,sales_invoice_comment,sales_invoice_item,sales_order,sales_order_address,sales_order_item,sales_order_payment,sales_order_status_history,sales_shipment,sales_shipment_comment,sales_shipment_item,sales_shipment_track,salesrule_coupon_aggregated,salesrule_coupon_aggregated_order,salesrule_coupon_aggregated_updated,search_query,session,translation,variable,variable_value
[2019-02-08 12:30:41][WARNING]: Destination documents are not mapped: email_template,paypal_billing_agreement,paypal_billing_agreement_order,quote,quote_address,quote_address_item,quote_item,quote_item_option,quote_payment,quote_shipping_rate,sales_creditmemo,sales_creditmemo_comment,sales_creditmemo_item,sales_invoice,sales_invoice_comment,sales_invoice_item,sales_order,sales_order_address,sales_order_item,sales_order_payment,sales_order_status_history,sales_shipment,sales_shipment_comment,sales_shipment_item,sales_shipment_track,salesrule_coupon_aggregated,salesrule_coupon_aggregated_order,salesrule_coupon_aggregated_updated,search_query,sw_dailydeals_dailydeal,translation,variable,variable_value,xxstore
[2019-02-08 12:30:41][WARNING]: Source fields are not mapped. Document: cms_page. Fields: root_template
[2019-02-08 12:30:41][WARNING]: Destination fields are not mapped. Document: cms_page. Fields: root_template
[2019-02-08 12:30:41][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-02-08 12:30:41][INFO][mode: data][stage: integrity check][step: Log Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-02-08 12:30:41][WARNING]: Source documents are not mapped: log_visitor
[2019-02-08 12:30:41][WARNING]: Destination documents are not mapped: customer_visitor
[2019-02-08 12:30:41][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-02-08 12:30:41][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
12% [===>------------------------] Remaining Time: < 1 secPHP Fatal error:  Uncaught Error: Call to a member function getStructure() on boolean in /var/www/m2.gocleaning.nl/vendor/magento/data-migration-tool/src/Migration/Step/ConfigurablePrices/Integrity.php:108
Stack trace:
#0 /var/www/m2.gocleaning.nl/vendor/magento/data-migration-tool/src/Migration/Step/ConfigurablePrices/Integrity.php(79): Migration\Step\ConfigurablePrices\Integrity->checkFields(Array, 'source')
#1 /var/www/m2.gocleaning.nl/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php(81): Migration\Step\ConfigurablePrices\Integrity->perform()
#2 /var/www/m2.gocleaning.nl/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php(92): Migration\Mode\AbstractMode->runStage(Object(Migration\Step\ConfigurablePrices\Integrity), 'ConfigurablePri...', 'integrity check')
#3 /var/www/m2.gocleaning.nl/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php(62): Migration\Mode\Data->runIntegrity(Object(Migration\App\Mode\StepList))
#4 /var/www/m2.gocleaning.nl/vendor/magento/data-migration-tool/src/Mig in /var/www/m2.gocleaning.nl/vendor/magento/data-migration-tool/src/Migration/Step/ConfigurablePrices/Integrity.php on line 108

**Comment by CharanjeetE** [comment]
Please help me to sort out these issues these are taking my too much time.

**Comment by victor-v-rad** [comment]
This error happens when M1 or M2 use prefix in tables name. Please add your prefix in config.xml file in tags
```
<source_prefix />
<dest_prefix />
```

**Comment by Charanjet** [comment]
I am not using any prefix in m1 and m2. All tables are with default name.

**Comment by Charanjet** [comment]
One thing I want to confirm that is it required to m1 to be in running state or just I can use database.

**Comment by Charanjet** [comment]
Please provide me solution for the first one question asked in starting. 
Also if settings migration are resulting in fail so can I do migrate core_config_data manually without any tool. If yes please suggest me how can I achieve this.

**Comment by victor-v-rad** [comment]
@CharanjeetE 
You probably configured source database = M2 and destination database = M1 in your config.xml. But it should be vice versa M1 is your source and M2 is your destination.
