### ISSUE TITLE
SessionHandler::read(): open() error after data migration

### ISSUE THREAD

**Issue by baljinderimpinge** [magento/data-migration-tool#702]
Hello @victor-v-rad 

I am getting error after migrating data to magento site. error is mentioned below:
`{"0":"Warning: SessionHandler::read(): open(\/var\/session\/sess_8lp0nbim068gmv711c0r81lfhc, O_RDWR) failed: No such file or directory (2) in \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/Session\/SaveHandler\/Native.php on line 22","1":"#0 [internal function]: Magento\\Framework\\App\\ErrorHandler->handler(2, 'SessionHandler:...', '\/var\/www\/html\/s...', 22, Array)\n#1 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/Session\/SaveHandler\/Native.php(22): SessionHandler->read('8lp0nbim068gmv7...')\n#2 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/Session\/SaveHandler.php(93): Magento\\Framework\\Session\\SaveHandler\\Native->read('8lp0nbim068gmv7...')\n#3 [internal function]: Magento\\Framework\\Session\\SaveHandler->read('8lp0nbim068gmv7...')\n#4 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/Session\/SessionManager.php(189): session_start()\n#5 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\Session\\SessionManager->start()\n#6 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\Session\\Generic\\Interceptor->___callParent('start', Array)\n#7 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\Session\\Generic\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#8 \/var\/www\/html\/sharbor\/mage2\/generated\/code\/Magento\/Framework\/Session\/Generic\/Interceptor.php(52): Magento\\Framework\\Session\\Generic\\Interceptor->___callPlugins('start', Array, Array)\n#9 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/Session\/SessionManager.php(130): Magento\\Framework\\Session\\Generic\\Interceptor->start()\n#10 \/var\/www\/html\/sharbor\/mage2\/generated\/code\/Magento\/Framework\/Session\/Generic\/Interceptor.php(14): Magento\\Framework\\Session\\SessionManager->__construct(Object(Magento\\Framework\\App\\Request\\Http), Object(Magento\\Framework\\Session\\SidResolver\\Proxy), Object(Magento\\Framework\\Session\\Config), Object(Magento\\Framework\\Session\\SaveHandler), Object(Magento\\Framework\\Session\\Validator), Object(Magento\\Framework\\Session\\Storage), Object(Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager), Object(Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory), Object(Magento\\Framework\\App\\State))\n#11 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(111): Magento\\Framework\\Session\\Generic\\Interceptor->__construct(Object(Magento\\Framework\\App\\Request\\Http), Object(Magento\\Framework\\Session\\SidResolver\\Proxy), Object(Magento\\Framework\\Session\\Config), Object(Magento\\Framework\\Session\\SaveHandler), Object(Magento\\Framework\\Session\\Validator), Object(Magento\\Framework\\Session\\Storage), Object(Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager), Object(Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory), Object(Magento\\Framework\\App\\State))\n#12 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(66): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Framewo...', Array)\n#13 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#14 \/var\/www\/html\/sharbor\/mage2\/generated\/code\/Magento\/Framework\/Session\/Generic\/Proxy.php(84): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#15 \/var\/www\/html\/sharbor\/mage2\/generated\/code\/Magento\/Framework\/Session\/Generic\/Proxy.php(207): Magento\\Framework\\Session\\Generic\\Proxy->_getSubject()\n#16 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/Url.php(981): Magento\\Framework\\Session\\Generic\\Proxy->getSessionIdForHost('http:\/\/10.91.0....')\n#17 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/Url.php(1129): Magento\\Framework\\Url->_prepareSessionUrl('http:\/\/10.91.0....')\n#18 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php(78): Magento\\Framework\\Url->getRedirectUrl('http:\/\/10.91.0....')\n#19 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#20 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php(73): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#21 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#22 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#23 \/var\/www\/html\/sharbor\/mage2\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#24 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#25 \/var\/www\/html\/sharbor\/mage2\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#26 \/var\/www\/html\/sharbor\/mage2\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#27 \/var\/www\/html\/sharbor\/mage2\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#28 {main}","url":"\/mage2\/","script_name":"\/mage2\/index.php"}`

Please check this issue asap and help me to solve this issue.
site: http://devsharbor.urtestsite.com/mage2/

Thanks

**Comment by baljinderimpinge** [comment]
Hello @victor-v-rad 

I am looking for your response.

Thanks
